version: '3'
services:
  prospect-pg:
    container_name: prospect-pg
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    image: postgres:15.2
    environment:
      POSTGRES_USER: prospect
      POSTGRES_PASSWORD: prospect
      POSTGRES_DB: gateway
    volumes:
      - prospect-data:/var/lib/postgresql/data/
      - "./docker-pg-init.sql:/docker-entrypoint-initdb.d/docker-pg-init.sql"
    ports:
      - '60662:5432'
    networks:
      - prospect
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "prospect", "-d", "gateway"]
      interval: 5s
      timeout: 5s
      retries: 5

  supertokens:
      image: registry.supertokens.io/supertokens/supertokens-postgresql:5.0
      depends_on:
        prospect-pg:
          condition: service_healthy
      ports:
        - '60663:3567'
      environment:
        POSTGRESQL_CONNECTION_URI: "postgresql://prospect:prospect@prospect-pg:5432/supertokens"
      networks:
        - prospect
      restart: unless-stopped
      healthcheck:
        test: >
          bash -c 'exec 3<>/dev/tcp/127.0.0.1/3567 && echo -e "GET /hello HTTP/1.1\r\nhost: 127.0.0.1:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
        interval: 10s
        timeout: 5s
        retries: 5
volumes:
  prospect-data:
networks:
  prospect:
    name: prospect
    driver: bridge
