version: '3'
services:
  prospect-gateway-pg:
    container_name: prospect-gateway-pg
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    image: postgres:15.2
    environment:
      POSTGRES_USER: prospect
      POSTGRES_PASSWORD: prospect
      POSTGRES_DB: prospect_nba_gateway
    volumes:
      - prospect-data:/var/lib/postgresql/data/ #using a volume
      # - ./.db/postgres-data:/var/lib/postgresql/data
      #- ./data:/var/lib/postgresql/data/ # if you want to use a bind folder
    ports:
      - '60662:5432'
    networks:
      - prospect
volumes:
  prospect-data:
networks:
  prospect:
    name: prospect
    driver: bridge
